# Nicks used in the 2018 freenode spam waves
SPAM = {'icee6', 'Strog5', 'Pilfers', 'aaron7', 'sabre104127', 'd10n4',
        'Jacob84310', 'rdococ24', 'mindjuju25', 'ZexaronS', 'Demp13',
        'jelly19', 'm', 'orliesaurus9', 'lutoma13', 'Miron6', 'Guest3871',
        'C0c0dril017', 'Meanderthal29', 'maskedlua25', 'of', 'poutine6',
        'mrBlaQ18', 'rory10', 'infernix14', 'Aleszandro', 'nortoh',
        'digitalcold5', 'apetresc12', 'Cajs13', 'walle303', 'Death9163',
        'linear', 'Xenthys15', 'Asorailahd', 'mattcode',
        'OvidiuS11', 'breitenj5', 'brackets0', 'samfty', 'boredguy',
        'ChickenSoup_', 'Ohelig22', 'drdanick1', 'Meanderthal0',
        'marcoslater', 'nemesys', 'Guest51933', 'arza12', 'RustyJ17',
        'newtmewt', 'zeroed11', 'spirit_pact', 'banzaikitten10', 'memoryno-',
        'letty18', 'Shibe14', 'qew', 'Ellenor6', 'thejoecarroll11', 'gamma2',
        'marduk1917', 'bananas24', 'missnomer7', 'niek', 'Xenthys20',
        'Turner92', 'ultrabong', 'oso96_200010', 'brand027', 'deedra23',
        'Guest85819', 'ozymandias23', 'Ishaq21', 'lunaaa', 'Pidgeotto10',
        'realz21', 'irinix7', 'if`m', 'noteness', 'TroniQ89', 'oldschool^1',
        'Krenair13', 'sulvone24', 'the_madman20', 'zhongfu18', 'Guest73213',
        'Warped14', 'wiggle', 'Guest38652', 'profall5', 'was',
        'BranchPredictor1', 'kaniini_', 'Corvus`28', 'fireworks3',
        'HeinzBoettjer', 'Guest3393', 'Neo21', 'Usurp25', 'ecrist1',
        'DenSchub29', 'tallguy19', 'EdSaperia26', 'danzilio5',
        'ccallahan5', 'Guest95115', 'Tojil', 'ripazha', 'Praise12',
        'fsamareanu2', 'Tyrantelf23', 'nedbat24', 'ckeltz7', 'mpmc11',
        'drot1', 'mentifis25', 'guest3546', 'grumble222', 'Nick`',
        'Guest81029', 'Croepha6', 'rogue', 'floogulinc2', 'sockspls17',
        'ghoti29', 'yano21', 'SakiiR0', 'kayamm25', 'poutine10',
        'Neobenedict', 'ynyounuo', 'Ryuzaki', 'GingerGeek25', 'tacocat20',
        'meti4', 'siinus`27', 'ozymandias24', 'kek918', 'Nietzsche13',
        'aOssed8', 'yawkat3', '^Phantom^', 'swordsmanz26', 'jamesl',
        'jorrakay17', 'Vlad9', 'Azure20', 'Goldman600', 'MeiR', 'thunderrd',
        'ThiefMaster19', 'Techman8', 'anataex', 'nkk71', 'Guest61806',
        'mww113', 'mozzarella22', 'Shibe19', 'Sophira0', 'programmerq24',
        'chalcedony13', 'phuzion27', 'cheshire_cat', 'crayfishx26',
        'Peetz0r28', 'MEPB', 'Reincarnate15', 'd10n3', 'kameloso10', 'evil',
        'iamtakingiteasy', 'Guest87713', 'possiblyanowl', 'pathfinder4',
        'mozzarella0', 'knolle29', 'GigabytePro24', 'DarthGandalf5',
        'nullcone', 'Evel-Knievel', 'Skunky5', 'peaches', 'richvdh14',
        'lynxis2', 'Vercas27', 'Waldo8', 'ikevin26', 'klx``19',
        'HarryCross218', 'casdr7', 'VM_', 'Guest92322', 'robotroll',
        'sekizo8', 'albel7270', 'Kinny2', 'XXXX'}

IGNORE = {'Spacenet', 'Pillownet'}
SKIP = SPAM | IGNORE

ALIASES = {
    'Goodjob': 'donut',
    'FiatSeicento': 'Fiat',
    'Fiat_Seicento': 'Fiat',
    'Fiat_Punto': 'Fiat',
    'FiatGrandePunto': 'Fiat',
    'senm': 'senmithrarin',
    'TidPleb': 'TidB',
    'TidKek': 'TidB',
    'TidNub': 'TidB',
    'TidPro': 'TidB',
    'TidSpam': 'TidB',
    'TidNope': 'TidB',
    'TidBuff': 'TidB',
    'TidNerf': 'TidB',
    'Ghafetti': 'TidB',
    'TidSHUTUP': 'TidB',
    'TipB': 'TidB',
    'Overwatch': 'TidB',
    'umm': 'TidB',
    'Niknub': 'TidB',
    'PECK-NECK': 'TidB',
    'TestdB': 'TidB',
    'smol_data': 'TidB',
    'VasyaTheWizard': 'karl37',
    'v4ssili': 'karl37',
    'WikiPan': 'Wookipan',
    'Wikipan': 'Wookipan',
    'Zeyklon': 'Zeklyn',
    'Zeyklno': 'Zeklyn',
}
